name: Deploy
on:
  workflow_run:
    workflows: ["Build and Push Images"]
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "ghcr.io/${{ github.repository_owner }}/product-service:latest"
          echo "ghcr.io/${{ github.repository_owner }}/order-service:latest"
